### ISSUE TITLE
Unordered lists aren't rendered correctly

### ISSUE THREAD

**Issue by chocolateboy** [JasonBarnabe/greasyfork#537]
[moved from a comment in #535]

#535 appears to have removed the indented bullets from unordered lists (on desktop) e.g.:

## Before

<a href="https://i.imgur.com/LDoGqqi.png" title="Before"><img alt="Before" src="https://i.imgur.com/LDoGqqi.png" /></a>

## After

<a href="https://i.imgur.com/gL814WL.png" title="After"><img alt="After" src="https://i.imgur.com/gL814WL.png" /></a>

This change appears to have been caused by the addition of this rule:

```css
#script-content ul {
    list-style-type: none;
    padding: 0;
}
```
